#if NETSTANDARD1_3
// ReSharper disable once CheckNamespace
namespace System.ComponentModel
{
    //
    // Summary:
    //     Provides a way to synchronously or asynchronously execute a delegate.
    public interface ISynchronizeInvoke
    {
        //
        // Summary:
        //     Gets a value indicating whether the caller must call System.ComponentModel.ISynchronizeInvoke.Invoke(System.Delegate,System.Object[])
        //     when calling an object that implements this interface.
        //
        // Returns:
        //     true if the caller must call System.ComponentModel.ISynchronizeInvoke.Invoke(System.Delegate,System.Object[]);
        //     otherwise, false.
        bool InvokeRequired { get; }

        //
        // Summary:
        //     Asynchronously executes the delegate on the thread that created this object.
        //
        // Parameters:
        //   method:
        //     A System.Delegate to a method that takes parameters of the same number and type
        //     that are contained in args.
        //
        //   args:
        //     An array of type System.Object to pass as arguments to the given method. This
        //     can be null if no arguments are needed.
        //
        // Returns:
        //     An System.IAsyncResult interface that represents the asynchronous operation started
        //     by calling this method.
        IAsyncResult BeginInvoke(Delegate method, object[] args);
        //
        // Summary:
        //     Waits until the process started by calling System.ComponentModel.ISynchronizeInvoke.BeginInvoke(System.Delegate,System.Object[])
        //     completes, and then returns the value generated by the process.
        //
        // Parameters:
        //   result:
        //     An System.IAsyncResult interface that represents the asynchronous operation started
        //     by calling System.ComponentModel.ISynchronizeInvoke.BeginInvoke(System.Delegate,System.Object[]).
        //
        // Returns:
        //     An System.Object that represents the return value generated by the asynchronous
        //     operation.
        object EndInvoke(IAsyncResult result);
        //
        // Summary:
        //     Synchronously executes the delegate on the thread that created this object and
        //     marshals the call to the creating thread.
        //
        // Parameters:
        //   method:
        //     A System.Delegate that contains a method to call, in the context of the thread
        //     for the control.
        //
        //   args:
        //     An array of type System.Object that represents the arguments to pass to the given
        //     method. This can be null if no arguments are needed.
        //
        // Returns:
        //     An System.Object that represents the return value from the delegate being invoked,
        //     or null if the delegate has no return value.
        object Invoke(Delegate method, object[] args);
    }
}
#endif